services:
  todo-php:
    container_name: todo-list-php
    build:
      context: sistema-legado-php/
      dockerfile: Dockerfile
    ports:
      - "40000:80"
    volumes:
      - ./sistema-legado-php/src/:/var/www/html/
  todo-express:
    container_name: todo-list-express
    build:
      context: backend-express/
      dockerfile: Dockerfile
    ports:
      - "40001:3000"
    volumes:
      - ./backend-express/src/:/app/src/
  todo-react:
    container_name: todo-list-react
    build:
      context: frontend-react/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react/src:/app/src
    environment:
      - WATCHPACK_POLLING=true

